spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-security
    username: elias
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # The create-drop starts with a clean database at the end of the session
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
